### ISSUE TITLE
Vaadin 22 - vaadin-element-mixin

### ISSUE THREAD

**Issue by hons82** [tarekoraby/collapsible-splitlayout#2]
In Vaadin 22 the element-mixin has been moved into `@vaadin/component-base/src/element-mixin.js` so you'll get the following error.

`Module not found: Error: Can't resolve '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js'`

There is no dependency in `package.json` on that. Maybe it's enough to add it there.

Btw there are a lot of dependencies in that `package.json` that might not be needed like `grid-pro` for instance.

**Comment by tarekoraby** [comment]
Thanks! Version 2.0.0 of the addon is now published to the Directory, and it should work with v22+.
